name: Selenium con JUnit - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21.0.1
      uses: actions/setup-java@v4
      with:
        java-version: 21.0.1
        distribution: 'adopt' 

    - run: mvn clean 
    - run: mvn install
    - run: mvn test



