name: Selenium con JUnit - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21.0.1
      uses: actions/setup-java@v3
      with:
        java-version: '21.0.1'
        distribution: 'adopt'

    - name: Download Edge WebDriver
      run: |
        wget https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/?form=MA13LH  -O edgedriver_win64.zip
        unzip edgedriver_win64.zip
        chmod +x msedgedriver.exe
        sudo mv msedgedriver.exe /usr/local/bin/
     
    - name: Build with Maven and Run Test
      run: mvn -B clean test


