name: Selenium con JUnit - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download and install Microsoft Edge WebDriver
      run: |
        curl -L https://msedgedriver.azureedge.net/120.0.2210.144/edgedriver_linux64.zip -o edgedriver.zip
        sudo unzip edgedriver_linux64.zip -d /usr/local/bin
        sudo chmod +x /usr/local/bin/msedgedriver

    - run: mvn clean 
    - run: mvn install
    - run: mvn test
