name: Selenium con JUnit - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11 (Selenium y Edge WebDriver son compatibles con JDK 11)
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Download and install Microsoft Edge WebDriver
      run: |
        EDGE_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_STABLE)
        curl -L https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver_linux64.zip -o edgedriver.zip
        sudo unzip edgedriver.zip -d /usr/local/bin
        sudo chmod +x /usr/local/bin/msedgedriver

    - run: mvn clean 
    - run: mvn install
    - run: mvn test
