name: Demo github action

on:
  push:
    branches:
      - main

jobs:
  demo_trabajo:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Demo 1 de GitHub Actions"